// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYrZhWV_swjG538ORnvPsRI6dTE9AH1C4',
    appId: '1:908971145881:web:71d75b53f5adca23f59608',
    messagingSenderId: '908971145881',
    projectId: 'food-kart-215fb',
    authDomain: 'food-kart-215fb.firebaseapp.com',
    storageBucket: 'food-kart-215fb.firebasestorage.app',
    measurementId: 'G-82L8EJMM3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDARbSHqtsZ-QkiT7tepYsPxOCWpUszCAo',
    appId: '1:908971145881:android:03f3d534ad707d6af59608',
    messagingSenderId: '908971145881',
    projectId: 'food-kart-215fb',
    storageBucket: 'food-kart-215fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdBJ7D0cPDenBvhFp3svB2cLRTTzZvD7Q',
    appId: '1:908971145881:ios:42e75383e662a8d9f59608',
    messagingSenderId: '908971145881',
    projectId: 'food-kart-215fb',
    storageBucket: 'food-kart-215fb.firebasestorage.app',
    iosBundleId: 'com.example.sgp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdBJ7D0cPDenBvhFp3svB2cLRTTzZvD7Q',
    appId: '1:908971145881:ios:42e75383e662a8d9f59608',
    messagingSenderId: '908971145881',
    projectId: 'food-kart-215fb',
    storageBucket: 'food-kart-215fb.firebasestorage.app',
    iosBundleId: 'com.example.sgp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYrZhWV_swjG538ORnvPsRI6dTE9AH1C4',
    appId: '1:908971145881:web:a309f1a17cba3348f59608',
    messagingSenderId: '908971145881',
    projectId: 'food-kart-215fb',
    authDomain: 'food-kart-215fb.firebaseapp.com',
    storageBucket: 'food-kart-215fb.firebasestorage.app',
    measurementId: 'G-BYJZ85PFJG',
  );
}
